georchestra/mapstore2-georchestra

- build.sh
Per https://github.com/georchestra/mapstore2-georchestra/issues/3#issuecomment-537822925 - otherwise chrome should be added to build requirements but that's a bit too much imo.
With that, i'm able to produce `web/target/GeOrchestra.war`
> only run tests if chrome is installed

- js/components/User.jsx
- js/plugins/Header.jsx
- themes/default/georchestra.less
Fixed tutorial setting tutorial overlay position to`fixed`.
Make also USER indicator not visible by default, (can be enabled via configuration, for testing purposes)
> #98 Fixed tutorial position. Removed GUEST/ADMIN indicator

- themes/default/georchestra.less
- themes/default/header.less
- themes/default/theme.less
This PR introduces a dedicated less file for styles dedicated to header integration.
This in order to isolate this changes for future common use in the other integrations like in this case:
https://github.com/geosolutions-it/geonode-mapstore-client/blob/4abf9e97932fc55a49b9f266e85fe776fed73bc1/geonode_mapstore_client/client/themes/preview/less/geonode.less
> #99 fixed bottom tools size

- Dockerfile
- backend/pom.xml
- backend/src/main/java/it/geosolutions/georchestra/ConfigLoader.java
- docs/source/database/index.rst
- docs/source/developer/index.rst
- docs/source/index.rst
- docs/source/security/index.rst
- js/app.jsx
- pom.xml
- web/pom.xml
- web/src/main/resources/applicationContext.xml
- web/src/main/resources/geostore-datasource-ovr.properties
- web/src/main/resources/geostore.properties
- web/src/main/webapp/WEB-INF/web.xml
- webpack.config.js
This is the list of externalized configuration (to be put in <georchestra.datadir>/mapstore):
* localConfig.json
* proxy.properties
* log4j.properties
* geostore.properties
* printing folder (config.yaml + resources)
A lot of configuration properties are also loaded from <georchestra.datadir>/default.properties
> #104: externalized configuration files

- js/pages/ContextCreator.jsx
- localConfig.json
- themes/default/georchestra.less
Restored original CSS solution for Toolbar and Background selector
removed feature grid from viewerPlugins
removed configurations that are uinuseful (equal to defaults)
> Fix context creator layout

- .github/workflows/mapstore.yml
Dunno what @geosolutions-it uses for CI, but @georchestra uses github actions since a month or so (see georchestra/georchestra#2931) - i've been tinkering with github actions on mapstore2-georchestra repo this morning, and finally got to a point where i have it building a war and making it available as an artifact, which allows to download a zip containing mapstore-$SHA.war.
I personally have zero interest in adding the goo for docker images/repo etc, but so far this fits my need (not having to pull/fetch/recompile locally).
@fvanderbiest what do you think about it ? @tdipisa do you have some plans wrt CI ?
> Use github actions for CI

- js/app.jsx
With this change everything related to extensions is loaded from the datadir instead of the mapstore folder, in particular:
* extensions.json
* pluginsConfig.json
* all the bundles and assets used by the extensions (js, translations)
Note that the plugin uploader already stores stuff in the datadir, this only enables loading them from there.
> Enables using extensions from the datadir

- docs/source/configuration/index.rst
- js/app.jsx
- localConfig.json
- web/src/main/resources/mapstore.properties
* #221 new.json and config.json can be put in datadir now
* #221 uploaded extensions can be stored outside of the datadir
* #54 enabled printing at fixed scales
* extensions upload UI error if file is not zip
**Note 1**: printing at fixed scales is done by properly configuring the Print plugin in localConfig.json.
It will not work for existing contexts, where the print plugin does not have these settings.
**Note 2**: to enable the uploaded extensions folder, a new JVM option need to be set, the option is called georchestra.extensions (e.g. -Dgeorchestra.extensions=/tmp/mapstore); if not set uploaded extensions will be put in the usual datadir
> Updated MapStore to latest to include some fixes

- docs/source/security/index.rst
- web/src/main/resources/geostore-spring-security.xml
This PR (needs an update of GeoStore/Mapstore as from this https://github.com/geosolutions-it/geostore/pull/207) allow to map headers role removing the `ROLE_` prefix, so groups match with prefixes
> Fixed role groups mapping

- localConfig.json
Add MapCatalog, Save and SaveAs plugin to default localConfig.json.
> #264: updated mapstore reference and default configuration

- web/pom.xml
- web/src/main/resources/log4j.properties
logging in georchestra was uniformized in georchestra/georchestra#1268, would be nice to have a similar config by default for mapstore. needs to be included in georchestra/datadir#186 too.
> Fix logging for consistency with other georchestra modules

- Dockerfile
to be sure that URI /mapstore is always the same
fixes #282
> Despite of original war name, make it mapstore.war

- .github/workflows/mapstore.yml
- README.md
- api.html
- apiTemplate.html
- docs/source/developer/integration/index.rst
- docs/source/index.rst
- embedded.html
- embeddedTemplate.html
- header.html
- index.html
- indexTemplate.html
- js/app.jsx
- package.json
- pom.xml
- prod-webpack.config.js
- version.txt
- web/pom.xml
- web/src/main/resources/geostore-spring-security.xml
- web/src/main/webapp/WEB-INF/web.xml
- webpack.config.js
This PR contains fixes on various strings in the project.
#2 
- changes all "GeOrchestra" to geOrchestra.
- changes the name of the finar `war` file from `GeOrchestra.war` to `mapstore.war` (because this is the final name of the war used).
Only the `package.json` now contains a `georchestra` string in package name, because it's standard for npm package to be all lower case. Of course all the strings with `somethingGeOrchestra`  will remain with capital `G`, because the capital indicates the separation between words
#287
- Replace loading spinner from "Loading geOrchestra" to "Loading"
- Window title from "geOrchestra" to "GeOrchestra Viewer".
> #2 Remove all capital g from geOrchestra strings

- localConfig.json
Accordingly to this issue https://github.com/geosolutions-it/MapStore2/issues/6477 `tools` is now an invalid property. Removing solves the problem identified in #332
> #332 Removed tools locate (now injected by plugin)

- localConfig.json
[Backport 1.2.x] #332 Removed tools locate (now injected by plugin) (#333)
> [Backport 1.2.x] #332 Removed tools locate (now injected by plugin) (#333)

- database/001_mapstore.sql
This PR fix #310 and allow to create and save context with install from ansible without docker (not yet reproduced with others env).
> Fix table and hibernate_sequence access denied

- localConfig.json
This PR adds to `localConfig.json` the embedded configuration, with "GoFull" plugin.
"Note": GoFull in "embedded" is intended to be used only in embedded maps (without context).
> #347 add embedded configuration with GoFull button

- js/app.jsx
This issue solves the problem of iframe + incognito mode caused by localStorage not accessible (depending on 3rd party cookies enable).
Draft until [this issue ](https://github.com/geosolutions-it/MapStore2/issues/6651) is solved (by [this](https://github.com/geosolutions-it/MapStore2/pull/6820) PR on master,  that need to be backported.
> #351: Fix issue with localStorage in incognito mode

- .github/workflows/mapstore.yml
In order to synchronize this repository with geOrchestra releases, I suggest to push the generated docker images issued by a created tag.
I did a try with a tag '20.1.3-georchestra' without checking the push step will only be executed when executed on the master branche, hence this PR.
> pushing tags (releases) docker images to docker hub

- .gitignore
- pom.xml
- web/pom.xml
This is to avoid having to install npm and launch it separately from maven.
> using frontend-maven-plugin for building js resources

- web/pom.xml
This follows the issue #405, and is willing to harmonize the way the artifacts are built in the other geOrchestra modules.
My suggestion for #405 would be to use the master branch and regularly tag "2x.z.t-georchestra" each time we need to release a new version of geOrchestra.
The following PR will the work this way. Using the following maven command into the web module:
```
% mvn clean package deb:package -PdebianPackage
```
This will produce the following debian package:
```
georchestra-mapstore_<closest tag name>-<number of commits since the previous tag>_all.deb
```
depending on how the CI is configured, we might want to only generate packages against a tag, not for each commits, as the previous packages will be discarded by reprepro when publishing.
@landryb I'm not quite sure of the …
> web module - Generates a debian package as artifact     

- .gitmodules
This PR switches the Mapstore2 submodule to a georchestra branch of the georchestra fork of Mapstore2. This allows to integrate recent developments that have been accepted and merged into Mapstore2 until updating the submodules to branch `2021.02.xx` which involves more obstacles.
> Switch Mapstore2 submodule to georchestra fork

- js/plugins/Version.jsx
- revision.js
Changed the repo-url and submodule-url in Version plugin to be get from configuration, and not by URL command.
This to avoid old versions of git to fail and to make it more stable (remotes can be customized, origin doesn't always indicate the current repo).
> #402 Made Version Repo-URLs configurable

- configs/pluginsConfig.json
With this PR Street view extension is not necessary anymore.
The street view tool is pulled directly from MapStore stable branch.
> Update to latest stable (Street View)

- web/pom.xml
This fixes a previous work from PR #407 ; the maven-resources-plugins copies resources to target/mapstore, but the debianPackage maven profile expects to generate a war file from target/mapstore-generic (as stated in the previous mentioned PR, this is a convention used in the other webapps from geOrchestra).
This commit suggests to externalize the target directory for resources to a variable, which is then overriden in the `debianPackage` maven profile.
It also adds extra resources to be excluded while copying. e.g if the maven-frontend-plugin is used, then a node/ subdirectory is created, we don't need it in the generated webapp, so it has been added to the excludes list, same for coverage.
Note: since no CI has been set up yet to generate the debian package, this is probably the reason …
> deb - fixing webapp generation

- .github/workflows/mapstore.yml
made possible by #446, while here improve `actions/checkout` usage for submodules
> publish a debian package artifact via gh-actions

- api.html
- apiTemplate.html
- embedded.html
- embeddedTemplate.html
- index.html
- indexTemplate.html
The issue here seems to be caused by a duplicated gmaps API loading, that have a conflict.
This because html files contain an old script tag to include gmaps API for google layers (not supported anymore). When street view tries to load, the application finds that the google API is already loaded, and so it doesn't load them a second time. 
This was not failing in previous versions, so maybe is due to recent changes to google libs.
> Fix streetview API key issue

- web/pom.xml
reworks what was done in #407, use the branch to determine if we're on master
or not, prepend 99 if that's the case, and use maven timestamp and short git
commit sha.
> use the same debian package version conventions as in georchestra (#463)

- configs/pluginsConfig.json
This PR adds fixes for:
- #462 : adds configurability for panorama options (sets as default for
new contexts the `imageDateControl: true`
- #399 : Adding contribution by @landryb to WMTS print option
> Pedastrian view and WMTS fixes

- web/pom.xml
use the same debian packaging version conventions as in georchestra
> backport #464 on 2021.02.xx (fixes #463)

- configs/localConfig.json
those have recently be opened up by IGN, cf (among others) https://geoservices.ign.fr/services-web-decouverte and https://geoservices.ign.fr/services-web-essentiels (https://geoservices.ign.fr/services-web-experts could be interesting too, i but i dont think the altimetry service would work for cesium/globe view)
i've been able to successfully test loading WMS and WMTS raster layers, and they worked ootb without having to fiddle with obscure query parameters. For some reason https://wxs.ign.fr/essentiels/geoportail/v/wms?service=WMS&version=1.3.0&request=GetCapabilities doesnt load in mapstore/timeouts.. and some of the services are redundant, this PR is mostly here to open discussion about whether some national services/layers should be added by default (i personally think it would be …
> localConfig.json: add some IGN geoservices to defaults

- .github/workflows/mapstore.yml
same as #496 
Fix https://github.com/georchestra/georchestra/issues/3501
CI was not creating tagged images probably because it relied on git tags rather than branches
should work for both now.
Also includes some (harmless?) modifications of variables of the CI, GITHUB_REF_NAME, VERSION (which was equal to github.ref_name)
> force CI to build and tag on branch name (#3501)

- configs/localConfig.json
This PR adds plugin config to enable `SearchByBookmark` feature
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
**What is the current behavior?**
#514
**What is the new behavior?**
SearchByBookmark is enabled in desktop version. It follows the default permissioning ie. plugin is enabled and visible only when user is authenticated
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
> #514: Added SearchByBookmark plugin to config

- themes/default/header.less
This PR adds fix to layout of bottom tools overlap when map viewer is displayed in modal
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
**What is the current behavior?**
#515 
**What is the new behavior?**
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
> #515: Bottom tools layout fix in modal

- themes/default/header.less
Ref: https://github.com/georchestra/mapstore2-georchestra/pull/517#issuecomment-1113241074
Fix for timeline tool layout when attribute table is opened.
Timeline plugin has inline style to apply position hence need to be overriden.
> #515: Timeline tool position fix

- configs/localConfig.json
- configs/pluginsConfig.json
This PR makes a slight change to configuration: an option to print overlay layers will be available by default in map viewer & will be preset by default to the printing module on context creation.
> Activate print overlay layers capability by default

- configs/localConfig.json
Context page have an independent key in localConfig to enlist plugins that should be loaded on context viewer by default.
This default list should have "Header" plugin because it's not configurable in context creation/edit wizard and can't be added or removed there.
> Include Header plugin on a context page by default

- web/src/main/resources/applicationContext.xml
As per [official guidelines](https://docs.mapstore.geosolutionsgroup.com/en/2022.02.xx/developer-guide/mapstore-migration-guide/#upgrading-the-printing-engine), adding missing updates not included in #561.
> Missing updates for printing

- web/pom.xml
- web/src/main/java/fr/lepuyenvelay/msiframe/MsIframeController.java
- web/src/main/webapp/WEB-INF/msIframe-servlet.xml
- web/src/main/webapp/WEB-INF/views/jsp/msiframe.jsp
- web/src/main/webapp/WEB-INF/web.xml
Following https://github.com/georchestra/mapstore2-georchestra/issues/476
As explained in our last call, I think this still the better alternative.
The API documentation is available here : https://gitlab.agglo-lepuyenvelay.fr/jusabatier/msiframe/-/blob/master/README.md
This way it's only added to the Georchestra's version as you said me that you don't want maintain it for Mapstore.
I still have some questions : 
- Is the setParams (POST) bugued on master ? 
When I tested, I redirect to it but it always redirect to : `/mapstore/#/viewer/openlayers/config?queryParamsID=###` even if I provide a page parameter.
**Edit : I investigated and found out that it may be due to my environment log level (DEBUG).
In Spring 5.1, 5.2 and probably 5.3 (the MS version), request logs can flush the request …
> Integrate msIframe connector

- js/plugins.js
With this PR we exclude BackgroundSelector from the list of modularPlugins, to avoid conflicts with UserSession. 
Locally this mode seems to solve #573
> #573 Made BackgroundSelector not modular

- js/plugins.js
[Backport 2022.02.xx] #573 Made BackgroundSelector not modular (#578)
> [Backport 2022.02.xx] #573 Made BackgroundSelector not modular (#578)

- README.md
as discussed in a meeting this morning with @catmorales and @jusabatier , we feel that it'd be better to enforce that rule for each release/release candidate. Sure, It calls for some testing, but there shouldn't be regressions from bugfixes, and this way we're more aligned with the stable branches of MapStore.
that topic was discussed in https://github.com/georchestra/mapstore2-georchestra/issues/573#issuecomment-1348680341 too but the stable update to MS 2022.02.02 (geosolutions-it/MapStore2@814ac152) was forgotten/missed when publishing the final https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-geOrchestra release which ships with geosolutions-it/MapStore2@15c079322f4ce44f73f957bd145a1bf209c695f2
Thus, we lack some bugfixes from …
> specify that for releases the MapStore submodule should be updated to the latest commit on the tracked stable branch

- web/pom.xml
it results in super verbose logging of REST queries on stderr when using the resulting WAR
thanks @pierrejego for the help :)
> exclude org.apache.cxf.Logger coming from geostore-webapp (fixes #586)

- themes/default/georchestra.less
- themes/default/header.less
This PR removes previously used overriden to position map toolbar, background selector and timline toolbar as these are not required anymore
- #378 
**Map/context viewer**
**Context-creator**
**Geostory - Map viewer modal**
> #378 - Style overrides removed

- js/epics/usersession.js
This PR fixes the user session by adding missing session props to custom sessionSelector
https://github.com/georchestra/mapstore2-georchestra/issues/378#issuecomment-1699327513
> #378: Fix - User session objects with featuregrid

- configs/pluginsConfig.json
- web/pom.xml
This PR updates MS submodule to latest of `2023.02.xx`
- #651 
<details>
<summary>
</summary>
**Note**: `zoomToLayer` is set to `false` for Catalog plugin (existing config) (COG layer won't zoom to extent when added with bbox)
</details>
> #651: Update MS to latest version (Phase III)

- Dockerfile
geOrchestra docker images are provided with unzipped webapps. 
The current PR aligns MapStore-georchestra docker image with the other ones.
Example direct benefit - custom themes are easier to implement using docker:
```
- ./themes:/usr/local/tomcat/webapps/mapstore/dist/themes
```
A multi stage build is used to reduce the final image size - it does not have to embed the original war file.
> docker - provide unzipped war

- js/epics/login.js
This PR handle redirection after login when login redirection was performed programatically (due to unauthorized access to a resource and not logged in). Previously requested resource is saved to localstorage and upon successful redirection (after login) the saved localstorage value is cleared
- https://github.com/georchestra/mapstore2-georchestra/issues/638#issuecomment-1670782515
> #638: Redirect to requested resource on login

- .gitignore
- Dockerfile
- georchestra-docker-scripts/docker-entrypoint.d/100-execute-custom-scripts.sh
- georchestra-docker-scripts/docker-entrypoint.sh
This PR adds the capability to run scripts at startup of the container.
It's a part of the georchestra PR :
- https://github.com/georchestra/georchestra/pull/4083
Soving issue : 
- https://github.com/georchestra/georchestra/issues/4030
Set  `CUSTOM_SCRIPTS_DIRECTORY` environment variable to point to a valid volume.
Set a volume with scripts to execute.
Example :
```
mapstore:
image: georchestra/mapstore:latest
...
volumes:
- georchestra_datadir:/etc/georchestra
environment:
- CUSTOM_SCRIPTS_DIRECTORY=/etc/georchestra/mapstore/scripts
```
> Implement custom scripts for mapstore

- .gitignore
- configs/localConfig.json
- index.html
- indexTemplate.html
- js/plugins/Header.jsx
- web/src/main/resources/mapstore.properties
https://github.com/georchestra/georchestra/pull/4065
Implements the new georchestra/header in geoserver.
Main PR : https://github.com/georchestra/georchestra/pull/4065
> Implemention of new WebComponent header

- .gitignore
- Dockerfile
- georchestra-docker-scripts/docker-entrypoint.sh
https://github.com/georchestra/mapstore2-georchestra/pull/671
https://github.com/georchestra/mapstore2-georchestra/pull/663
> backport header and custom scripts changes to 2022.02.xx

- .gitignore
- api.html
- apiTemplate.html
- embedded.html
- embeddedTemplate.html
- geostory-embedded-template.html
- geostory-embedded.html
- index.html
- indexTemplate.html
This PR is used to change favicon to point to `/favicon.ico` url.
This is supposed to be the default location for geOrchestra's favicon.
Resolving : 
- https://github.com/georchestra/georchestra/issues/4087
In order to change default location, we can implement it with a custom script, modyfing `/favicon.ico` infollowing html files to the new location using  a tool like `sed`. 
Files to change : 
```
./webapps/mapstore/embedded.html
./webapps/mapstore/api.html
./webapps/mapstore/embeddedTemplate.html
./webapps/mapstore/geostory-embedded.html
./webapps/mapstore/index.html
./webapps/mapstore/dist/embedded.html
./webapps/mapstore/dist/geOrchestra.js
./webapps/mapstore/dist/geostory-embedded.html
./webapps/mapstore/dist/index.html
./webapps/mapstore/indexTemplate.html …
```
> Favicon location

- configs/localConfig.json
- js/plugins/Header.jsx
- web/src/main/resources/mapstore.properties
Main PR :
- https://github.com/georchestra/georchestra/pull/4120
This PR adds missing 'logo-url' attribute and new 'stylesheet' attribute
> Themable Webcomponent header

- web/src/main/resources/log4j2.component.properties
only point at log4j2.properties in the georchestra datadir, apparently that property doesn't have the support for config path priorities
fixes #662
> fix logging configuration path by adding a missing / (#662)

- configs/localConfig.json
- js/plugins.js
- js/plugins/EasyTheming.jsx
- js/plugins/Header.jsx
- themes/default/variables.less
This PR allows to use another css file (and keeping mapstore context themes) without the need to rebuild app. 
CSS file must be provided with another web server and link must be added in `index.html` and `indexTemplate.html`
Example of sh file to update it :
```sh
#!/bin/sh
INDEX_DIR=${1:-/usr/local/tomcat/webapps/mapstore/}
SNIPPET="<link rel='stylesheet' href='/public/georchestra.css'>"
if grep -q "${SNIPPET}" "${INDEX_DIR}/indexTemplate.html"; then
echo "[INFO] geOrchestra: stylesheet already present"
exit 0
fi
echo "[INFO] geOrchestra: add geOrchestra stylesheet..."
sed -i "s#<body>#<body>${SNIPPET}#" ${INDEX_DIR}/index.html
sed -i "s#<body>#<body>${SNIPPET}#" ${INDEX_DIR}/indexTemplate.html
```
Example of css file : 
```css
/* This file is used to override the default geOrchestra …
```
> Allow theming mapstore with another css file

- web/pom.xml
update:
- maven-war-plugin to 3.4.0
- mockito-core to 4.0.0
with geosolutions-it/MapStore2#9851 this allows me to build mapstore2-georchestra with java17, which is the default java version on debian 12.
> fix build with java 17

- Dockerfile
- docker/server.xml
PR hides tomcat version in error pages. I added a server.xml because port is different upstream `8082` instead of `8080` for docker.
@tdipisa Don't know if it's relevant to propose it upstream. 
Code involved :
```
<Valve className="org.apache.catalina.valves.ErrorReportValve"
showReport="false"
showServerInfo="false"/>
```
> Add tomcat server xml to hide version

- Dockerfile
update based on PR https://github.com/georchestra/mapstore2-georchestra/pull/442
> Run tomcat as non-root user

- docs/source/developer/index.rst
cf #712 & 713, still work in progress
cc @f-necas @tkohr @pierrejego @Gaetanbrl
> Improve developer documentation

- webpack.config.js
allows testing features restricted to connected users
/cas correctly proxies to cas, but /whoami still replies `{"GeorchestraUser":null}` so the header shows the login button.
@f-necas : using:
```
-const DEV_HOST = "localhost:8080";
+const DEV_HOST = "georchestra.example.org:8180";
```
the page header still doesnt show me the logged in button, while mapstore itself shows me the plugins restricted to an admin user (eg save/delete/etc etc) so the authenticated requests to `/rest` work with `sec-username`/`sec-roles` only.
what were the headers necessary for `/whoami` to correctly find the user ? against a throwaway instance i can't figure that out...
```
curl -H sec-username:testadmin -H sec-proxy:true -H sec-roles:ROLE_MAPSTORE_ADMIN -H sec-org:C2C \
-H 'sec-orgname: Test Org' …
```
> set sec-username/sec-roles in webpack proxy config

- .github/workflows/backport.yml
- indexTemplate.html
Closes https://github.com/georchestra/mapstore2-georchestra/issues/728
Remove proj4.js to use local implementation
Temporary keep es5.js with cdn 
Add backport bot to use label for backport.
> Remove proj4.js to use local implementation, also add backport

- .github/workflows/mapstore.yml
- Dockerfile
Solves Cgroup2 problem with. 
JDK uses temurin now
> fix: bump docker to 9-jdk
