localConfig.json

* Added new coordinate systems to localConfig
* Modified CRSSelector options
Issue: #9

#9 Map Zone - Multiple CRS support

---

config.json
localConfig.json
new.json

Adds :
- default backgrounds to background selector
- OSM GeoBretagne as default background

#75 setup default background fixes

---

js/app.jsx
js/plugins.js
localConfig.json

This PR 
- Fixes path to context-editor
- updates MapStore to support redirect to `#/admin` after context save
- Add back to back to manager button (admin) and setup omnibar to fill the top in context-editor

#76 Fixed paths, redirects and add exit button

---

js/plugins.js
localConfig.json

- Removed 3D switcher
- Fixed wrong import of  "MapImport" plugin.

Fixed map export plugin, removed 3d map switcher

---

themes/default/header.less
themes/default/theme.less

This PR fixes the style for the import div in the _not full window size_ context

#97 add style customization for import div

---

index.html
indexTemplate.html
jsconfig.json
themes/default/header.less

Removed z-index of the header to avoid issues with back-masks or displacement of windows. Updated mapstore to fix other issues. Removed unneded code (issue with import is now solved by fixing z-index of header, override is not needed anymore
Fixes issues: 
- #94 local code
- #95 update MS
- #115 update MS

Fix black masks issues. Updated MS #94 #95 #115

---

localConfig.json

Just because that's something that i keep adding locally when testing, and it also shows that not only CSW is supported :)

add local geoserver to default services

---

docs/source/georchestra_integration/index.rst
docs/source/index.rst

Most of the parts in this documentation can probably be translated in single pull requests for the following repos:
https://github.com/georchestra/docker
https://github.com/georchestra/datadir
https://github.com/georchestra/georchestra/tree/master/header
I also suggest to set MapStore so it automatically populates the database it needs, instead of pointing to the GeoStore documentation

MapStore2 integration documentation

---

docs/source/georchestra_integration/index.rst

Updated docker JAVA_OPTS to current values.

#145: fixes for the integration documentation

---

js/plugins.js
localConfig.json

Update to latest master. 
Update also config for #184

Update to latest master. Update config and plugins for #184

---

localConfig.json
package.json

Update to latest changes on master branch

Updated to master

---

config.json
new.json

Updated to latest reference, added empty background on new.json and config.json

Add empty background - Update to latest mapstore

---

js/plugins.js
localConfig.json
pluginsConfig.json
web/pom.xml

Port changes for 
- #48  
- #197 
- #46 
- #45 
- #36 only localStorage based

Updated to latest master

---

localConfig.json
package.json

Update to latest master + TOC metadataOptions configuration added.
#50

Show Layer Metadata - Layer metadata

---

js/actions/__tests__/usersession-test.js
js/actions/usersession.js
js/epics/__tests__/usersession-test.js
js/epics/usersession.js
js/plugins/UserSession.jsx
js/reducers/__tests__/usersession-test.js
js/reducers/usersession.js

https://github.com/georchestra/mapstore2-georchestra/issues/36#issuecomment-625222957

#36: fixed reset of additional session info (templates and userPlugins)

---

localConfig.json
new.json
pluginsConfig.json

Updated to close the following issues (and removed not working layer in new.json)
#231 : updated links for cookie URLs
#30 
#221 
#50 
#48 
#45

Update 12 05 2020

---

.github/workflows/mapstore.yml
README.md

Upgrad npm minimal version to 12 in order to avoid memory problems.

Upgrade npm

---

js/plugins.js
localConfig.json
pluginsConfig.json

Add minor fixes and improvements. Error handling for failing extensions

updated to latest MapStore

---

web/pom.xml

Waiting for all checks passed.

#305: Updated to stable back-end services

---

web/pom.xml

Use the correct version names for geostore-webapp and http_proxy

Fixed wrong versions on pom.xml

---

web/pom.xml

This PR align to latest stable branch.

Update with latest stable

---

package.json
version.txt
web/.settings/org.eclipse.core.resources.prefs
web/.settings/org.eclipse.jdt.apt.core.prefs
web/.settings/org.eclipse.jdt.core.prefs
web/.settings/org.eclipse.m2e.core.prefs

- updates to recent fixes on MapStore (minor bug fixes). 
- align package.json
- small cleanup of eclipse files.

Updated to latest stable. Small cleanup

---

localConfig.json

Add 3D switcher to localConfig.json by default

3d plugin added to localConfig.json 

---

package.json

Include fixes for: 
- #331 
- #328

Update latest stable

---

package.json

[Backport 1.2.x] Update latest stable (#341) #342

[Backport 1.2.x] Update latest stable (#341)

---

pom.xml
web/pom.xml

This  update the version of back-end used and correctly build the most recent version before install.

#344 Update package dependency. Invert build order

---

embedded.html
embeddedTemplate.html
js/embedded.jsx
localConfig.json
prod-webpack.config.js
webpack.config.js

This PR updates reference for MapStore and add embedded entry point for embedded maps without a specific context.

#355. Update to latest stable, fixed embedded issues

---

embedded.html
embeddedTemplate.html
js/embedded.jsx
localConfig.json
prod-webpack.config.js
webpack.config.js

[Backport 1.2.x] #355. Update to latest stable, fixed embedded issues (#356)

---

js/app.jsx

[Backport for 1.2.x] #351: Fix issue with localStorage in incognito mode (#365)

---

index.html
indexTemplate.html

Solves issues notified in #374  ( https://github.com/geosolutions-it/MapStore2/issues/6127) and Cesium certificate issue https://github.com/geosolutions-it/MapStore2/issues/6838

#374 Aligned to latest master

---

translations/data.en-US.json
translations/data.fr-FR.json
translations/data.it-IT.json

linked to https://github.com/geosolutions-it/MapStore2/pull/6845

overload for "Applications Catalog"

---

translations/data.en-US.json
translations/data.fr-FR.json
translations/data.it-IT.json

Backport of:
overload for "Applications Catalog" (#377)
Fixed translations and updated to latest stable (#382)

Backport translations mapcatalog

---

README.md

This PR includes : 
* More info about NodeJS install and specify NodeJS >14.x is not fully compatible (see #396)
* Change titles and create steps to follow
⚠️ Not sur to target master branch... if not, what is correct branch for external PR (workflow) ?

Reorganize readme, infos about NodeJS >14.x

---

README.md
js/plugins.js
js/plugins/Version.jsx
package.json
prod-webpack.config.js
revision.js
themes/default/georchestra.less
translations/data.en-US.json
translations/data.fr-FR.json
translations/data.it-IT.json
version.txt
webpack.config.js

This PR adds custom version component to Settings
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
##Issue
**What is the current behavior?**
#401 
**What is the new behavior?**
- `Mapstore2-geOrchestra` version and commit information is pulled in during build 
- `Mapstore2` submodule version alone is added to `version.txt` and commit information is pulled in during build
**Sample**
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

#401: Versioning repository and submodule

---

revision.js
web/src/main/webapp/WEB-INF/web.xml

Fixing a missing entry in `web.xml` for the loadAsset servlet.

add upload servlet  to servlet mapping

---

revision.js
web/src/main/webapp/WEB-INF/web.xml

Adding a missing servlet-mapping to web.xml

Update web.xml add to servlet mapping

---

package.json

This PR should fix the build for the stable branch adding a missing dependency.

Fixed build adding md5 dependency

---

web/pom.xml

the name end up in the debian package, so better use something 'nicer' - while here updated the project URL, since i dont think its correct right now, at least hidden, @tdipisa ?

update name and url values to align with reality

---

configs/pluginsConfig.json

[Backport 2021.02.xx] Pedestrian view and WMTS fixes (#471)

[Backport 2021.02.xx] Pedestrian view and WMTS fixes (#471)

---

js/app.jsx

Adds create map by context functionality
#437

Add entry point in react router for map created by context

---

dashboard-embedded-template.html
dashboard-embedded.html
geostory-embedded-template.html
geostory-embedded.html
js/dashboardEmbedded.jsx
js/geostoryEmbedded.jsx
prod-webpack.config.js
webpack.config.js

This PR corrects configuration of embedded GeoStories and Dasboards for MapStore GeOrchestra project.
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
#483 
**What is the current behavior?**
Attempt to embed GeoStory/Dashboards leads to an error.
**What is the new behavior?**
Dashboard or GeoStory is correctly loaded when it's embedded into another page.
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

#483 Proper configuration for embedded geostories and dashboards.

---

dashboard-embedded-template.html
dashboard-embedded.html
geostory-embedded-template.html
geostory-embedded.html
js/dashboardEmbedded.jsx
js/geostoryEmbedded.jsx
prod-webpack.config.js
webpack.config.js

[Backport 2021.02.xx] Proper configuration for embedded geostories and dashboards. (#483)

[Backport 2021.02.xx] Proper configuration for embedded geostories and dashboards. (#483)

---

.github/workflows/mapstore.yml

Backport of #490 for stable branch

Update mapstore.yml (#490)

---

configs/localConfig.json
configs/pluginsConfig.json

Missing part of the changes related to the updated layout. 
With the applied changes sidebar menu will be active by default for desktop on map viewer.
Context wizard plugin dependencies are updated.

Update of config files to includes sidebar menu by default

---

web/src/main/resources/applicationContext.xml

Removes the file uri prefix from the log4j configurer.

remove file: prefix from log4j configurer

---

web/pom.xml

- change geostore and mapstore versions to snapshot

geostore and mapstore to snapshot

---

configs/config.json
configs/new.json

- Proper fix of the white globe on the cesium viewer (data directory need to be checked if it redefines these files)
- Contexts on the home page - pencil button opens context editor wizard.

548 Resolving minor issues

---

README.md

This PR updates README.md with the steps needed for pre-release and release creation.

Release procedure documentation proposal

---

.github/workflows/mapstore.yml
pom.xml
web/pom.xml

Add artifactory deployement

---

pom.xml
web/pom.xml

from geosolutions-it/austrocontrol-C125#304 via geosolutions-it/MapStore2#8764
will see if the resulting war has one or two jackson versions..

ensure jackson lib version is 2.13.1 (fixes #603)

---

.github/workflows/mapstore.yml
pom.xml

> ref #608
This PR will fix the build process if we just follow the README (thanks @pierrejego).

#608 Insert maven compiler version

---

.github/workflows/mapstore.yml
pom.xml

Print layer with visibility limits applied #585

---

configs/localConfig.json

cc @fvanderbiest @tkohr - with that we're aligned with https://github.com/georchestra/datadir/blob/master/mapstore/configs/localConfig.json with georchestra/datadir#308 merged.

merge localConfig.json changes from georchestra datadir

---

configs/localConfig.json
js/app.jsx
web/pom.xml
web/src/main/resources/proxy.properties
web/src/main/webapp/WEB-INF/web.xml

This PR updates MS submodule to latest of MS (master)
- #627

#627: Update to 2023.02

---

configs/localConfig.json

This PR adds missing configurations
- To show Delete menu option in Geostory and Dashboard
- Show advanced settings center and zoom option in Share plugin when map is 3D

Added missing configurations

---

js/epics/usersession.js

**Description**
This PR adds the missing backport from Phase III

[Backport 2023.02.xx] #378: Fix - User session objects with featuregrid #649

---

Dockerfile

backport of #664 on 2023.02.xx

docker - provide unzipped war

---

.gitignore
Dockerfile
georchestra-docker-scripts/docker-entrypoint.sh

https://github.com/georchestra/mapstore2-georchestra/pull/671
https://github.com/georchestra/mapstore2-georchestra/pull/663

backport header and custom scripts changes to 2023.02.xx

---

configs/localConfig.json

mostly georchestra/datadir@ee445cdf and georchestra/datadir#367

sync localConfig.json with commits in the georchestra/datadir project

---

configs/localConfig.json

mostly georchestra/datadir@ee445cdf and georchestra/datadir#367

[2023.02.xx] backport #680

---

docs/source/index.rst
docs/source/msiframe/index.rst
web/src/main/webapp/WEB-INF/views/jsp/msiframe.jsp

This allow to set layer's title to use in TOC from msiframe GET request.
I also added some documentation on how to use it in the doc.
@tdipisa @landryb Can someone with write permission merge this update ?

Allow to set title from msiframe

---

configs/localConfig.json

This PR updates MS submodule to include improvements on annotation circle geometry
- #645 
- #681

#645 & #681: Fix - Annotations circle geometry

---

web/src/main/resources/log4j2.component.properties

[2023.02.xx] backport #689

---

web/pom.xml

This PR updates MS submodules to include the fix for #681

#681 - Fix: Circle radius is modified when saving the annotation

---

configs/config.json
configs/localConfig.json
web/pom.xml

This PR updates MS submodules to include Phase IV issues and #679
- https://github.com/georchestra/mapstore2-georchestra/issues/647
- https://github.com/georchestra/mapstore2-georchestra/issues/682
- https://github.com/georchestra/mapstore2-georchestra/issues/646
- https://github.com/georchestra/mapstore2-georchestra/issues/644
- https://github.com/georchestra/mapstore2-georchestra/issues/645
- https://github.com/georchestra/mapstore2-georchestra/issues/681
- https://github.com/georchestra/mapstore2-georchestra/issues/679

[Backport 2023.02.xx] Update MS submodule to include Phase IV and #679

---

.github/workflows/mapstore.yml
DOCKER_HUB.md

To fill all docker hub documentation 
Main PR :
- https://github.com/georchestra/georchestra/pull/4135

Add Docker-hub documentation

---

configs/localConfig.json

This PR updates the catalog service types to include IFC Model & ArcGIS
https://github.com/georchestra/mapstore2-georchestra/issues/714#issuecomment-2437713391

Catalog service types updated

---

database/001_mapstore.sql

cf https://github.com/geosolutions-it/geostore/blob/master/doc/sql/migration/postgresql/postgresql-migration-from-v.2.0.0-to-v2.1.0.sql

update sample sql for schema 2.1.0. Fixes #719

---

database/001_mapstore.sql

Add PERMALINK to SQL File

---

Dockerfile

Related to https://github.com/georchestra/georchestra/issues/4354 and https://github.com/georchestra/helm-georchestra/pull/127

Update resource management in Dockerfile

---

web/pom.xml

This PR updates the MS submodule to include a fix for creating circle annotations with a form radius on map click

Circle annotation with form radius

---

web/pom.xml

Circle annotation with form radius (#736)

[Backport 2024.02.xx] Circle annotation with form radius (#736)
